spring:
  profiles.active: dev
  main:
    allow-bean-definition-overriding: true  
  datasource:
    url: jdbc:postgresql://localhost/dbdemo
    driverClassName: org.postgresql.Driver
    username: postgresql
    password: inside
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      show-sql: true
      hibernate:
        format_sql: true
      javax:
        persistence:
          create-database-schemas: true
          #schema-generation
            #scripts
              #action: create
              #create-target: create.sql
              #create-source: metadata
  batch:  
    initialize-schema: always
    job:
      enabled: true    
   
    # http://localhost:8080/h2-console
    #spring.h2.console.enabled=true
    #url: jdbc:h2:mem:testdb
    #driverClassName: org.h2.Driver
    #username: sa
    #password: password
    #ipa.database-platform=org.hibernate.dialect.H2Dialect


---
logging:
  file:
    name: comuni-italiani-batch.log
  pattern:
    # http://logback.qos.ch/manual/layouts.html    console: "[%d][%-7level] [%-50.50C] [%-30.30M] %msg%n"
    file: "[%d][%-20thread][%-7level] [%-60C{1}][%-40M] %msg%n"
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR   