excel:
  fileName: 20210101_Elenco-comuni-italiani.xls
  sheetName: CODICI al 01_01_2021
  columnsMapping:
    CODICE_REGIONE_COL: 0
    CODICE_PROVINCIA_COL: 2
    PROGRESSIVO_COMUNE_COL: 3
    CODICE_COMUNE_COL: 4
    DENOMINAZIONE_COMUNE_COL: 6
    CODICE_RIPARTIZIONE_GEOGRAFICA_COL: 8
    RIPARTIZIONE_GEOGRAFICA_COL: 9
    DENOMINAZIONE_REGIONE_COL: 10
    SIGLA_AUTOMOBILISTICA_COL: 14
    CODICE_CATASTALE_COMUNE_COL: 19
  list:
    - item1
    - item2
    - item3
    - item4